### PR TITLE
Use generator function

### PR DESCRIPTION
**Pull request by fregante**
I don’t know if it’s equivalent. Just trying

### CODE REVIEW

**Comment by fregante** [comment]
Whoah, neat. 

- Sent from my iPhone

**Comment by sindresorhus** [comment]
Hehe. See https://github.com/sindresorhus/chunkify/pull/2.

**Comment by fregante** [comment]
Does that mean that I ~~found~~ *highlighted* a hole in the tests? 😏

**Comment by sindresorhus** [comment]
> Does that mean that I found highlighted a hole in the tests? 😏

Seems so.

// @jajaperson

**Pull request closed without merging**
